### ISSUE TITLE
secrets-store.csi.k8s.com should be renamed to secrets-store.csi.x-k8s.io

### ISSUE THREAD

**Issue by mikedanese** [deislabs/secrets-store-csi-driver#141]

**Comment by ritazh** [comment]
@mikedanese this was addressed in https://github.com/deislabs/secrets-store-csi-driver/pull/134
Do you see specific issues with the current implementation?

**Comment by mikedanese** [comment]
I still see it in a few spots on master:

https://github.com/deislabs/secrets-store-csi-driver/blob/54d117b8907d37e5c1f022b49ca4044cbc63bf37/deploy/csidriver.yaml#L4

https://github.com/deislabs/secrets-store-csi-driver/blob/54d117b8907d37e5c1f022b49ca4044cbc63bf37/cmd/secrets-store-csi-driver/main.go#L29

Full list:

```
deploy/csidriver.yaml
4:  name: secrets-store.csi.k8s.com

deploy/secrets-store-csi-driver.yaml
30:                    "rm -rf /registration/secrets-store.csi.k8s.com-reg.sock",

README.md
5:The Secrets Store CSI driver `secrets-store.csi.k8s.com` allows Kubernetes to mount multiple secrets, keys, and certs stored in enterprise-grade external secrets stores into their pods as a volume. Once the Volume is attached, the data in it is mounted into the container's file system.
126:secrets-store.csi.k8s.com  0s
236:          driver: secrets-store.csi.k8s.com

cmd/secrets-store-csi-driver/main.go
29:     driverName         = flag.String("drivername", "secrets-store.csi.k8s.com", "name of the driver")

test/bats/tests/nginx-pod-secrets-store-inline-volume.yaml
16:        driver: secrets-store.csi.k8s.com

test/bats/tests/nginx-pod-secrets-store-inline-volume-crd.yaml
16:        driver: secrets-store.csi.k8s.com

test/bats/tests/nginx-pod-vault-inline-volume-secretproviderclass.yaml
16:        driver: secrets-store.csi.k8s.com

test/sanity/sanity_test.go
35:             driver.Run("secrets-store.csi.k8s.com", "somenodeid", endpoint, providerVolumePath)

charts/secrets-store-csi-driver/templates/csidriver.yaml
4:  name: secrets-store.csi.k8s.com

charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml
32:                    "rm -rf /registration/secrets-store.csi.k8s.com-reg.sock",
```

**Comment by ritazh** [comment]
These are the csi driver name `secrets-store.csi.k8s.com`, which will be updated to `secrets-store.csi.k8s.io` https://github.com/deislabs/secrets-store-csi-driver/issues/129 per sig-storage review comment [here](https://github.com/deislabs/secrets-store-csi-driver/issues/100#issuecomment-553207654)

**Comment by mikedanese** [comment]
Ah ok, thanks. Looks like this is covered by other bugs then.

**Comment by ritazh** [comment]
Just to clarify, we cant update the name until after the repo move.
